### ISSUE TITLE
Monitor queues using wildcard

### ISSUE THREAD

**Issue by optimistic5** [rabbitmq/rabbitmq-prometheus#31]
Now I have this alert for Prometheus:
```
- alert: RabbitmqTooManyMessagesInQueue
    expr: rabbitmq_queue_messages_ready{queue="my-queue"} > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Rabbitmq too many messages in queue (instance {{ $labels.instance }})"
      description: "Queue is filling up (> 1000 msgs)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
```
Notice than I have:
`{queue="my-queue"}`

To monitor all queues I can use this line, **right**?
`rabbitmq_queue_messages_ready`

But I want to monitor queues using wildcard.
For example:
`{queue="guest_*"}`

**Now I need to add each queues separately, but it is a lot of them and new queues becomes often.
This feature will help a lot.** 
Thank you.
